service: juanArancibia-practicoIntegrador

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev

plugins:
  - serverless-iam-roles-per-function

functions:
  - ${file(src/create-client/create-client.yml)}
  - ${file(src/assign-card/assign-card.yml)}
  - ${file(src/assign-gift/assign-gift.yml)}

resources:
  # Tables
  - ${file(resource/tables/clients.yml)}

  # Topics
  - ${file(resource/topics/client-created.yml)}

  # Queues
  - ${file(resource/queues/assign-card.yml)}
  - ${file(resource/queues/assign-gift.yml)}
