service: juanArancibia-practicoIntegrador

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev

plugins:
  - serverless-iam-roles-per-function

functions:
  - ${file(src/create-client/create-client.yml)}
  - AssignGift:
      handler: assign-gift/index.handler
      name: ${self:service}-${self:provider.stage}-assign-gift-function
      environment:
        CLIENTS_TABLE: !Ref ClientsTable
      iamRoleStatementsInherit: true
      iamRoleStatementsName: juanCastroArancibia-integrador-assign-gift
      iamRoleStatements: 
        - Effect: Allow
          Action:
            - dynamodb:UpdateItem
          Resource:
            - !GetAtt ClientsTable.Arn
      events:
        - sqs:
            arn: !GetAtt AssignGiftQueue.Arn

  - AssignCard:
      handler: assign-card/index.handler
      name: ${self:service}-${self:provider.stage}-assign-card-function
      environment:
        CLIENTS_TABLE: !Ref ClientsTable
      iamRoleStatementsName: juanCastroArancibia-integrador-assign-card
      iamRoleStatementsInherit: true
      iamRoleStatements: 
        - Effect: Allow
          Action:
            - dynamodb:UpdateItem
          Resource:
            - !GetAtt ClientsTable.Arn
      events:
        - sqs:
            arn: !GetAtt AssignCardQueue.Arn

resources:
  Resources:
    ClientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-clients-table
        AttributeDefinitions:
          - AttributeName: dni
            AttributeType: S
        KeySchema:
          - AttributeName: dni
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    ClientCreatedTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Client Created Topic
        TopicName: ${self:service}-${self:provider.stage}-client-created-topic
        Subscription:
          - Protocol: sqs
            Endpoint: !GetAtt AssignCardQueue.Arn
          - Protocol: sqs
            Endpoint: !GetAtt AssignGiftQueue.Arn

    AssignCardQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-assign-card-queue
    
    AssignCardQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties: 
        PolicyDocument: 
          Statement:
            - Effect: Allow
              Action: 
                - SQS:*
              Resource: !GetAtt AssignCardQueue.Arn
              Principal:
                AWS:
                  - !Ref AWS::AccountId
            - Effect: Allow
              Principal:
                AWS: 
                  - '*'
              Action: 
                - SQS:SendMessage
              Resource: !GetAtt AssignCardQueue.Arn
              Condition:
                ArnLike:
                  aws:SourceArn:
                    - !Ref ClientCreatedTopic
        Queues: 
          - !Ref AssignCardQueue

    AssignGiftQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-assign-gift-queue
    
    AssignGiftQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties: 
        PolicyDocument: 
          Statement:
            - Effect: Allow
              Action: 
                - SQS:*
              Resource: !GetAtt AssignGiftQueue.Arn
              Principal:
                AWS:
                  - !Ref AWS::AccountId
            - Effect: Allow
              Principal:
                AWS: 
                  - '*'
              Action: 
                - SQS:SendMessage
              Resource: !GetAtt AssignGiftQueue.Arn
              Condition:
                ArnLike:
                  aws:SourceArn:
                    - !Ref ClientCreatedTopic
        Queues: 
          - !Ref AssignGiftQueue
