service: juanArancibia-practicoIntegrador

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev

plugins:
  - serverless-iam-roles-per-function

functions:
  - ${file(src/clients/create-client/create-client.yml)}
  - ${file(src/clients/update-client/update-client.yml)}
  - ${file(src/clients/delete-client/delete-client.yml)}
  - ${file(src/clients/get-all-clients/get-all-clients.yml)}
  - ${file(src/clients/get-client/get-client.yml)}

  - ${file(src/clients/assign-card/assign-card.yml)}
  - ${file(src/clients/assign-gift/assign-gift.yml)}

resources:
  # Tables
  - ${file(resource/tables/clients.yml)}
  - ${file(resource/tables/purchases.yml)}

  # Topics
  - ${file(resource/topics/client-created.yml)}

  # Queues
  - ${file(resource/queues/assign-card.yml)}
  - ${file(resource/queues/assign-gift.yml)}
  - ${file(resource/queues/add-points.yml)}
