Resources:
  AssignCardQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-assign-card-queue

  AssignCardQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      PolicyDocument: 
        Statement:
          - Effect: Allow
            Action: 
              - SQS:*
            Resource: !GetAtt AssignCardQueue.Arn
            Principal:
              AWS:
                - !Ref AWS::AccountId
          - Effect: Allow
            Principal:
              AWS: 
                - '*'
            Action: 
              - SQS:SendMessage
            Resource: !GetAtt AssignCardQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn:
                  - !Ref ClientTopic
      Queues: 
        - !Ref AssignCardQueue
