Resources:
  ClientTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Client Created/Updated Topic
      TopicName: ${self:service}-${self:provider.stage}-client-topic
      Subscription:
        - Protocol: sqs
          Endpoint: !GetAtt AssignCardQueue.Arn
        - Protocol: sqs
          Endpoint: !GetAtt AssignGiftQueue.Arn
        - Protocol: email
          Endpoint: 'juan.castro.arancibia@gmail.com'
